# Site
repository: Hammerill/hammerill.github.io
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: Kirill Petrov
title: Student of LycÃ©e Vieljeux
email: www.hammerill@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: Hammerill
github_username:  Hammerill
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: hammerill_inst
linkedin_username: Hammerill
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/Hammerill
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Bonjour!
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Kirill, I live in ðŸ‡«ðŸ‡· France, I'm from ðŸ‡ºðŸ‡¦ Ukraine and this is the facts about me:
  - ðŸŽ“ I Was studying in private IT academy [IT Step](https://mariupol.itstep.org/) for 2 years. 
  Couldn't finish degree due to the war. 
  Branch - IT programmer, several languages and technologies:
    * C++
    * C# (.NET, ASP.NET Core)
    * Python
    * HTML+CSS+JS
    * Java
    * etc...
  - ðŸµ Also a lot of time was directed to self-study.
  - ðŸ« In september of 2022 started studying in LycÃ©e LÃ©once Vieljeux, La Rochelle, France, computer science object.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Sand-Box2D
        link: https://github.com/Hammerill/Sand-Box2D
        link_text: View at GitHub
        additional_links:
          # - title:  View at GitHub
          #   icon: fab fa-github
          #   url: https://github.com/Hammerill/Sand-Box2D
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An open source cross-platform game based on Box2D with SDL2.
        description: | # this will include new lines to allow paragraphs
          ![Logo](./images/Sand-Box2D.jpg)
          
          This project was developed mainly for educational purposes. I've started developing it for myself just to understand basis of Box2D, how to link it with SDL2 and etc. But then, I've realized it could be more than just some rewritten code: a game. So, I took [this project](https://github.com/eder13/Box2D-SDL2-Demo) as the base, have rewritten it from zero using OOP, and now you're free to play this game and use its code at way as you want
      
      # - layout: top-middle
      #   title: uMario Vita
      #   link: https://github.com/Hammerill/uMario_Vita
      #   link_text: View at GitHub
      #   additional_links:
      #     # - title: View at GitHub
      #     #   icon: fab fa-github
      #     #   url: https://github.com/Hammerill/uMario_Vita
      #     - title: Get on VitaDB
      #       icon: fab fa-playstation
      #       url: https://vitadb.rinnegatamante.it/#/info/830
      #   quote: >
      #     Another uMario port for PSVita.
      #   description: | # this will include new lines to allow paragraphs
      #     ![Logo](./images/uMario_Vita.jpg)
          
      #     Just port, another port of this game. The fact that this port to PS Vita already was created before also surprised me.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
