repository: Hammerill/hammerill.github.io
favicon: images/favicon.ico

version: 2

name: Kirill (Kyrylo) Petrov
title: Student of LycÃ©e Vieljeux
email: www.hammerill@gmail.com

darkmode: true

twitter_username: Hammerill
github_username:  Hammerill
instagram_username: hammerill_inst
linkedin_username: kirill-petrov-42b609245

additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/Hammerill

about_title: Bonjour!
about_profile_image: images/profile.jpg
about_content: |
  My name is Kirill, I live in ðŸ‡«ðŸ‡· France, I'm from ðŸ‡ºðŸ‡¦ Ukraine and this is the facts about me:
  - ðŸŽ“ I Was studying in private IT academy [IT Step](https://mariupol.itstep.org/) for 2 years. 
  Couldn't finish degree due to the war. 
  Branch - IT programmer, several languages and technologies:
    * C++
    * C# (.NET, ASP.NET Core)
    * Python
    * HTML+CSS+JS
    * Java
    * etc...
  - ðŸµ Also a lot of time was directed to self-study.
  - ðŸ« In september of 2022 started studying in LycÃ©e LÃ©once Vieljeux, La Rochelle, France, computer science object.

content:
  - title: Projects
    layout: list
    content:
      - title: Sand-Box2D
        border: weak
        layout: top-middle
        # link: https://github.com/Hammerill/Sand-Box2D
        # link_text: GitHub
        additional_links:
          - title:  GitHub
            icon: fab fa-github
            url: https://github.com/Hammerill/Sand-Box2D
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An open source cross-platform game based on Box2D with SDL2.
        description: |
          [![Logo](./images/Sand-Box2D.jpg)](https://github.com/Hammerill/Sand-Box2D)

          This project was developed mainly for educational purposes. I've started developing it for myself just to understand basis of Box2D, how to link it with SDL2 and etc. But then, I've realized it could be more than just some rewritten code: a game. So, I took [this project](https://github.com/eder13/Box2D-SDL2-Demo) as the base, have rewritten it from zero using OOP, and now you're free to play this game and use its code at way as you want.
      
      - title: uMario Vita
        border: weak
        layout: top-middle
        # link: https://github.com/Hammerill/uMario_Vita
        # link_text: GitHub
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Hammerill/uMario_Vita
          - title: Get on VitaDB
            icon: fab fa-playstation
            url: https://vitadb.rinnegatamante.it/#/info/830
        quote: >
          Another uMario port for PSVita.
        description: |
          [![Logo](./images/uMario_Vita.jpg)](https://github.com/Hammerill/uMario_Vita)

          Just port, another port of this game. The fact that this port to PS Vita already was created before also surprised me.

      - title: TelegramBotTranslator
        border: weak
        layout: top-middle
#         link: https://github.com/Hammerill/TelegramBotTranslator
#         link_text: GitHub
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Hammerill/TelegramBotTranslator
        quote: >
          Telegram bot written in C# that translates text from many languages using GoogleAPI.
        description: |
          My test project of using .NET with EntityFW, Telegram bots, SQLite, JSON parser and etc.

          It's kinda outdated right now. I need to make a "revived" version later.
      

footer_show_references: false

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
